Repository kvassAI/slate, pull requests merged in 2019-02, with the labels that each got.

#124 Adding a description for the flag "is_prorated"
  source/includes/_plans.md
Labels: Waiting For Review, review

#125 fixing data type definitions
  source/includes/_users.md
Labels: Waiting For Review

#120 Stripe warning add/update card
  source/includes/_payment_methods.md
Labels: Waiting For Review, enhancement
